# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

version: 2

workflows:
  version: 2
  docs-build:
    jobs:
      - docs-build
      - docs-build-deploy:
          filters:
            branches:
              only: main

jobs:

  # Documentation CI
  docs-build:
    docker:
      - image: cimg/python:3.13

    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-python3.13-{{ checksum "pyproject.toml" }}-{{ checksum "setup.py" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-python3.13-

      - run:
          name: Install parsons
          command: |
            uv sync \\
              --upgrade \\
              --no-default-groups \\
              --group docs \\
              --all-extras

      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-python3.13-{{ checksum "pyproject.toml" }}-{{ checksum "setup.py" }}

      - run:
          name: Build docs
          command: |
            uv sync \\
              --no-default-groups \\
              --group docs \\
              --all-extras

            cd docs/
            make deploy_docs

  docs-build-deploy:
    docker:
      - image: cimg/python:3.13-node

    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-python3.13-{{ checksum "pyproject.toml" }}-{{ checksum "setup.py" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-python3.13-

      - run:
          name: Install parsons
          # Note that we the circleci node image installs stuff with a user "circleci", rather
          # than root. So we need to tell npm where to install stuff.
          command: |
            npm set prefix=/home/circleci/npm
            npm install -g --silent gh-pages@2.0.1

            uv sync \\
              --upgrade \\
              --no-default-groups \\
              --group docs \\
              --all-extras

      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-python3.13-{{ checksum "pyproject.toml" }}-{{ checksum "setup.py" }}

      - add_ssh_keys:
          # This SSH key is "CircleCI Docs" in https://github.com/move-coop/parsons/settings/keys
          # We need write access to the Parsons repo, so we can push the "gh-pages" branch.
          fingerprints:
            - '9a:ec:4d:2b:c3:45:b2:f5:55:ca:0b:2b:36:e2:7f:df'

      - run:
          name: Build and deploy docs
          # When running gh-pages, we specify to include dotfiles, so we pick up the .nojerkyll file.
          # (This file tell Github Pages that we want to include all files in docs/, including those
          # that start with an underscore like _static/).
          command: |
            uv sync \\
              --no-default-groups \\
              --group docs \\
              --all-extras

            cd docs/
            make deploy_docs

            cd ..

            git config user.email "ci-build@movementcooperative.org"
            git config user.name "ci-build"

            export PATH=/home/circleci/npm/bin:$PATH

            gh-pages --dotfiles --message "[skip ci] Updates" --dist docs
