# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

version: 2

workflows:
  version: 2
  test:
    jobs:
      - python_3.8
      - python_3.9
      - python_3.10

template: &template
  docker:
    - image: ubuntu:22.04
  working_directory: ~/repo
  steps:

    - checkout

    # Install Python version
    - run:
        name: install python $PYTHON_VERSION
        command: |
          sudo apt-get install python$PYTHON_VERSION
          
    # Download and cache dependencies
    - restore_cache:
        keys:
          - v2-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

    - run:
        name: install dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

    - save_cache:
        paths:
          - ./venv
        key: v2-dependencies-{{ checksum "requirements.txt" }}

    - run:
        name: run tests
        command: |
          . venv/bin/activate
          TESTING=1 pytest -rf test/

    - run:
        name: check linting
        command: |
          . venv/bin/activate
          # E203 and W503 don't work well with black
          flake8 parsons/ test/ useful_resources/ --extend-ignore=E203,W503
          black --check parsons/ test/ useful_resources/

    - store_artifacts:
        path: test-reports
        destination: test-reports

jobs:
  python_3.8:
    <<: *template
    environment:
      PYTHON_VERSION: 3.8
  python_3.9:
    <<: *template
    environment:
      PYTHON_VERSION: 3.9
  python_3.10:
    <<: *template
    environment:
      PYTHON_VERSION: 3.10

  # Documentation CI
  docs-build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-python3.10-{{ checksum "./docs/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-python3.10-
      - run:
          name: Install dependencies
          # Note that we the circleci node image installs stuff with a user "circleci", rather
          # than root. So we need to tell npm where to install stuff.
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r ./docs/requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-python3.10-{{ checksum "./docs/requirements.txt" }}
      - run:
          name: Build docs
          command: |
            . venv/bin/activate
            cd docs/
            make deploy_docs
            cd ..

  docs-build-deploy:
    docker:
      - image: cimg/python:3.10-node
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-python3.10-{{ checksum "./docs/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-python3.10-
      - run:
          name: Install dependencies
          # Note that we the circleci node image installs stuff with a user "circleci", rather
          # than root. So we need to tell npm where to install stuff.
          command: |
            npm set prefix=/home/circleci/npm
            npm install -g --silent gh-pages@2.0.1
            python3 -m venv venv
            . venv/bin/activate
            pip install -r ./docs/requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-python3.10-{{ checksum "./docs/requirements.txt" }}
      - add_ssh_keys:
          # This SSH key is "CircleCI Docs" in https://github.com/move-coop/parsons/settings/keys
          # We need write access to the Parsons repo, so we can push the "gh-pages" branch.
          fingerprints:
            - '9a:ec:4d:2b:c3:45:b2:f5:55:ca:0b:2b:36:e2:7f:df'
      - run:
          name: Build and deploy docs
          # When running gh-pages, we specify to include dotfiles, so we pick up the .nojerkyll file.
          # (This file tell Github Pages that we want to include all files in docs/, including those
          # that start with an underscore like _static/).
          command: |
            . venv/bin/activate
            cd docs/
            make deploy_docs
            cd ..
            git config user.email "ci-build@movementcooperative.org"
            git config user.name "ci-build"
            export PATH=/home/circleci/npm/bin:$PATH
            gh-pages --dotfiles --message "[skip ci] Updates" --dist docs
