name: Documentation CI/CD

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - major-release

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            files.pythonhosted.org:443
            github.com:443
            pypi.org:443

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          # If it's a push (main or major-release) or workflow_dispatch, get full history.
          fetch-depth: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && 0 || 1 }}

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: '3.13'
          cache: pip

      - uses: install-pinned/uv@259f91feb61b6e94766d7a1dbcd5f17335370e64

      - run: |
          uv pip install --system -e .[all]
          uv pip install --system -r requirements-dev.txt

      - name: configure git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306
        with:
          path: docs/_build/.doctrees
          key: sphinx-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements-dev.txt') }}

      - run: make build_docs
        working-directory: docs

      - uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b
        with:
          path: docs/html/

  deploy:
    needs: build
    # Only run this job if triggered by updating the main branch
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9
        with:
          disable-sudo: true
          egress-policy: audit

      - uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e
